export const LOGIN_IN = 'LOGIN_IN';
export const SET_AUTH = 'SET_AUTH';
export const ADD_PRODUCT_CATEGORY = 'ADD_PRODUCT_CATEGORY';
export const REMOVE_PRODUCT_CATEGORY = 'REMOVE_PRODUCT_CATEGORY';
export const ADD_PRODUCT = 'CREATE_PRODUCT';
export const ADD_PRODUCT_TO_CATEGORY = 'ADD_PRODUCT_TO_CATEGORY';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const IS_FETCHING = 'IS_FETCHING';
